apiVersion: v1
kind: Template
labels:
  app: apache
  template: apache-buildconfig
message: |-
  For more information about using this template, see https://github.com/Worteks/wsweet-ci
metadata:
  annotations:
    description: Apache Base Image - BuildConfig
      see https://github.com/Worteks/docker-apache
    iconClass: icon-openshift
    openshift.io/display-name: Apache Base
    openshift.io/documentation-url: https://github.com/Worteks/wsweet-ci
    openshift.io/provider-display-name: Worteks
    openshift.io/support-url: https://www.worteks.com
    tags: apache
  name: apache-buildconfig
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      description: Builds Wsweet Apache images
    labels:
      name: apache-${FRONTNAME}-${APACHE_REPOSITORY_REF}
    name: apache-${FRONTNAME}-${APACHE_REPOSITORY_REF}
  spec:
    failedBuildsHistoryLimit: 1
    resources:
      limits:
        cpu: 500m
        memory: 768Mi
    source:
      contextDir: /
      git:
        uri: ${APACHE_REPOSITORY_URL}
        ref: "${APACHE_REPOSITORY_REF}"
      type: Git
    strategy:
      type: Docker
      dockerStrategy:
        env:
        - name: DO_UPGRADE
          value: foo
        forcePull: false
    output:
      to:
        kind: ImageStreamTag
        name: apache-${FRONTNAME}:${APACHE_REPOSITORY_REF}
    triggers:
    - type: ConfigChange
parameters:
- name: APACHE_REPOSITORY_REF
  description: Set this to a branch name, tag or other ref of your repository if you are not using the default branch
  displayName: Git Reference
  required: true
  value: master
- name: APACHE_REPOSITORY_URL
  description: The URL of the repository with your Apache Dockerfile
  displayName: Git Repository URL
  required: true
  value: https://github.com/Worteks/docker-apache.git
- name: FRONTNAME
  description: The name identifier assigned to objects defined in this template
  displayName: Name
  required: true
  value: demo
